### ISSUE TITLE
difficulty running this

### ISSUE THREAD

**Issue by Dprofeta86** [scottleibrand/gpt-summarizer#10]
Thank you for sharing this - I am new with python and I am having difficulties running this as I receive an error saying: 

File "/Users/__/Desktop/summarize.py", line 151
    headers = [f"{section_header.split('.')[0]}. Section intro"]
                                                              ^
SyntaxError: invalid syntax
Any chance you would be able to help me figure this one out?

Just out of curiosity, is this compiled using python3? 
Thank you.

**Comment by scottleibrand** [comment]
I believe that f”” syntax is python3, yes. What version are you using? You might want to ask ChatGPT how to set up a Python virtual environment on Windows so you can load all the right versions of things for each project.

**Comment by Dprofeta86** [comment]
amazing - it worked!! Thank you!
