### ISSUE TITLE
Output in other languages

### ISSUE THREAD

**Issue by okneze** [scottleibrand/gpt-summarizer#3]
Hey there,

again, thanks for this great script!

Just want to share what I did to have the output in other language (for me in german)

I just changed 6 locations of "Please provide a detailed summary of the" into "Please provide a detailed summary in german of the" in lines 451, 520 and 584

Perhaps you can build this into the script as a parameter....

Many greetings from germany

Olli

**Comment by scottleibrand** [comment]
Nice! I was expecting to hear that you had prompted it with something like “Bitte geben Sie eine detaillierte Zusammenfassung der”, but if asking in English for a summary in German works just as well, then we could easily add a command-line language selector flag and include that into the English prompt like you did manually, if present.

You could probably even get ChatGPT to do it for you, if you’d like to PR the change. Labeling this as a good first issue to see if someone wants to pick that up and try it.

**Comment by scottleibrand** [comment]
Good work, thanks! I also updated the README to indicate how to use the new language selection feature.
